# [‰∏çÁî® root ‰ΩøÁî®Â∞èÁà±ÂêåÂ≠¶Âíå ChatGPT ‰∫§‰∫íÊäòËÖæËÆ∞](https://github.com/yihong0618/gitblog/issues/258)

## ‰ªéÂÜôÂú®ÂâçÈù¢
È°πÁõÆÈìæÊé• -> https://github.com/yihong0618/xiaogpt
Â§ßÂ§öÊï∞‰∫ãÂÑøÂæàÁÆÄÂçïÁöÑ‰∏Ä‰∏™ÁªìËÆ∫ÊòØÔºöËøô‰πàÂÅöÊúâ‰ªÄ‰πàÁî®Ôºü
‰ΩÜÊòØÔºåÊ≤°Áî®Â∞±‰∏çÂÅö‰∫Ü‰πàÔºüÂ•ΩÁé©‰πüÊòØÊúâÁî®‰πã‰∏ÄÂëÄ„ÄÇ

## Ê≥®

‰∏ãÊñá‰∏≠ revChatGPT ÊñπÊ°àÂ∫üÂºÉ‰∫ÜÔºåÂÖ®ÈÉ®ÊîπÁî® API, ËØ∑ÂèÇËÄÉ repo.

## ÊÉ≥Ê≥ï

- ‰ªé ChatGPT Âàö‰∏äÁ¨¨‰∫åÂë®ÂºÄÂßãÔºåÊàëÂºÑ‰∫Ü‰∏™Ë¥¶Âè∑ÔºåÂêéÊù•ÂèëÁé∞‰∏Ä‰∏™ÂæàÂ•ΩÁé©ÁöÑÈ°πÁõÆ [ChineseAiDungeonChatGPT](https://github.com/bupticybee/ChineseAiDungeonChatGPT) --> Áî® ChatGPT Áé© DND, ÊàëÁ™ÅÁÑ∂ÊÉ≥ÊàëËÉΩËØ≠Èü≥Â∞±Êõ¥ÊúâÂ∏¶ÂÖ•ÊÑü‰∫Ü„ÄÇ
- Âõ†‰∏∫‰πãÂâçÊäòËÖæ [blue](https://github.com/yihong0618/blue) Êó∂ÂÄô‰∫ÜËß£‰∫Ü‰∏Ä‰∫õÂ∞èÁ±≥ IOT ËÆæÂ§áÁöÑ‰∫§‰∫í tts, ÊàëËßâÂæóÊàëÁî®‰∏Ä‰∫õÊñπÂºèÊòØÂèØ‰ª•ÂÆûÁé∞ÁöÑ
- ‰∏çËøá‰ªéÊÉ≥Ê≥ïÂà∞ÂèØÁî®Á°ÆÂÆûÁªèÂéÜ‰∫Ü‰∏çÂ∞ë

## ÂºÄÂßãÊäòËÖæ

1. ÊúÄÊó©ÁöÑ idea ÊòØÊääÂ∞èÁà±ÂêåÂ≠¶Á†¥Ëß£‰∫ÜÔºåÁ†¥Ëß£‰πãÂêéÊã¶Êà™ÊàëÁöÑÂØπËØùÔºåÂ¶ÇÊûúÂØπËØùÂåÖÂê´ `GPT` Â∞±Áî®Á†¥Ëß£ÁöÑÂ∞èÁà±ÂèëÈÄÅËØ∑Ê±ÇÂà∞ ChatGPT, ÂÜçÊää ChatGPT ÁöÑÂõûÂ§çÊà™ÂåÖÔºåËØªÂá∫Êù•„ÄÇ
- ÈÅáÂà∞ÊúÄÂ§ßÁöÑÂõ∞ÈöæÊòØÂ∞èÁà±ÊÄé‰πàÁ†¥Ëß£ÔºåÊêú‰∫Ü‰∏ÄÂúàÂèëÁé∞ÔºåÂ∞èÁà±ÊòØÊúâÂäûÊ≥ïÈÄöËøá‰∏≤Âè£Êù• hook ÂÜçÂà∑Âõ∫‰ª∂ÁöÑ„ÄÇ
- ‰ΩÜ‰∏≤Âè£ÊòØÂï•ÔºüÊàëÂ≠¶‰π†‰∫Ü‰∏≤Âè£ÈÄö‰ø°ÔºåÁî®Ëá™Â∑±Ê†ëËéìÊ¥æÂÅöÂÆûÈ™åÔºåÂéªÊ∑òÂÆù‰π∞ usb2ttl Â≠¶‰ºö‰∫Ü„ÄÇ‰ΩÜÊòØÈúÄË¶ÅÁÑäÊé•ÔºåÊàëÂèàÂéª B Á´ôÂà∑ËßÜÈ¢ëÂ≠¶‰π†ÔºåÈóÆÂêå‰∫ãÁ°¨‰ª∂Â§ßÁ•ûÂ¶Ç‰ΩïÁÑäÊé•ÔºåÂ≠¶‰ºö‰∫ÜÁÑäÊé•„ÄÇ‰ΩÜÔºå‰ªñÂ¶àÁöÑÔºåÊñ∞ÁöÑÂ∞èÁà±ÂêåÂ≠¶Êää‰∏≤Âè£ÈÄö‰ø°ÁªôÂ∞Å‰∫Ü„ÄÇ
- ÁøªÂà∞‰∫Ü‰∏Ä‰∏™ÂõΩÂ§ñÁ†¥Ëß£Â∞èÁà±ÂêåÂ≠¶ÁöÑÔºå[ËÉΩÁî®ÊãÜÊú∫ÂêéÁöÑ USB Êù•ÁÉßÂõ∫‰ª∂](https://github.com/duhow/xiaoai-patch/blob/master/research/lx06/install.md)Ôºå‰ΩÜÊàëÊ≤°Êúâ windowsÔºå-> Â≠¶‰π†ËÄÅÁöÑ macbookpro 2015 Âà∑ÂèåÁ≥ªÁªüÔºåÂ∞ùËØïÁªôÂ∞èÁà±Âà∑Êú∫ -> Â∞èÁ±≥ÊääËøô‰∏™‰πüÂ∞Å‰∫Ü
- ÊúâË∂£ÁöÑÊòØÊØèÂ§©Áî®ÂèëÁé∞Á°ÆÂÆûËøòÊå∫Â•ΩÁî®ÁöÑÔºåËÆ©‰ªñÊîæÊ≠åÔºåÁªôÊàëÂÑøÂ≠êÊîæÂ∞èÁå™‰Ω©Â•á„ÄÇ‰∫éÊòØÂèàÁªô‰∏àÊØçÂ®ò‰π∞‰∫Ü‰∏Ä‰∏™ÔºåÁªôÂ•πÈÖçÁΩÆÂ•ΩÔºåÂèØ‰ª•ÊîæÊ≠å„ÄÇ

2. Á¨¨‰∏Ä‰∏™ÊñπÂºè‰∏çÂ§™Ë°åÔºåÂ∞ùËØïÂéªÁî®Ë∑ØÁî± openwrt Êà™ÂåÖÂÜçÂèëÈÄÅÔºå‰æùÁÑ∂Â§±Ë¥•ÔºåÊàëÊäòËÖæ‰∫Ü‰∏Ä‰∏ãÂèëÁé∞ https Ëé∑Âèñ payload ËøòÊòØÊúâ‰∫õÂõ∞ÈöæÁöÑ
3. ËΩ¨Âêë‰∫Ü Siri  ÈÇ£‰πàÊàëËÉΩ‰∏çËÉΩÁî® Siri  ÂÆûÁé∞Âë¢ÔºüÊòØËÉΩÁöÑÔºåÂèØ‰ª•Áî® Siri  -> Êç∑ÂæÑ -> Ëé∑Âèñ‰Ω†ËØ¥ÁöÑËØù -> ÂèëÈÄÅ ChatGPT -> Â∞èÁà± or Áõ¥Êé• Siri Ëá™Â∑±Êù•
4. ÁΩëÂèã[Ë±°ÁâôÂ±±ÂàòËÉΩ](https://twitter.com/disksing)Êúâ‰∏ÄÂ§©Âèë‰ªñÂÑøÂ≠êÂ∞èÁà±ÂêåÂ≠¶ÁöÑËÅäÂ§©ËÆ∞ÂΩïÔºåÁ™ÅÁÑ∂ÁÅµÊÑüÊù•‰∫ÜÔºåÊàëÂèØ‰ª•Áî®ÊúÄË†¢ÁöÑËΩÆËØ¢ÔºåÊù•‰∏çÊñ≠Ëé∑ÂèñÊúÄÊñ∞ÁöÑËÅäÂ§©ËÆ∞ÂΩïÔºåÂ¶ÇÊûúÊúâÊñ∞ÁöÑÁ¨¶ÂêàË¶ÅÊ±ÇÊàëÂ∞±ÂèëÈÄÅÁªô ChatGPT --> ÂÜçÁî® tts ËÆ©Â∞èÁà±ÂêåÂ≠¶ÊúóËØªÔºå‰ΩÜÂõ†‰∏∫ÊúóËØªÈúÄË¶ÅÊó∂Èó¥ÔºåÊâÄ‰ª•ËΩÆËØ¢‰πüÊ≤°ÈÇ£‰πàÁ¨®‰∫Ü„ÄÇ

## ÂÆûÁé∞

- ÂÖàÂÆûÁé∞‰∏çÊñ≠ÊãøÂØπËØùÂéÜÂè≤
- ÊµãËØï revChatGPT ÂèØË°å
- Âà©Áî® MiService call tts ÂèØË°å
- Ââ©‰∏ãÂ∞±ÊòØÂÜô‰ª£Á†Å‰∫Ü

## ÂáÜÂ§á

1. ChatGPT id
2. Â∞èÁà±Èü≥Âìç
3. ËÉΩÊ≠£Â∏∏ËÅîÁΩëÁöÑÁéØÂ¢ÉÊàñ proxy
4. python3.8+

## ‰ΩøÁî®

1. pip install -r requirements.txt
2. ÂèÇËÄÉ [MiService](https://github.com/Yonsm/MiService) È°πÁõÆ README Âπ∂Âú®Êú¨Âú∞ terminal Ë∑ë `micli list` ÊãøÂà∞‰Ω†Èü≥ÂìçÁöÑ DID ÊàêÂäü **Âà´Âøò‰∫ÜËÆæÁΩÆ export MI_DID=xxx** Ëøô‰∏™ MI_DID Áî® 
3. ÂèÇËÄÉ [revChatGPT](https://github.com/acheong08/ChatGPT) È°πÁõÆ README ÈÖçÁΩÆ chatGPT ÁöÑ config
4. run `python xiaogpt.py  --hardware ${your_hardware}` hardware ‰Ω†ÁúãÂ∞èÁà±Â±ÅËÇ°‰∏äÊúâÂûãÂè∑ÔºåËæìÂÖ•ËøõÊù•
5. Ë∑ëËµ∑Êù•‰πãÂêéÂ∞±ÂèØ‰ª•ÈóÆÂ∞èÁà±ÂêåÂ≠¶ÈóÆÈ¢ò‰∫ÜÔºå‚ÄúÂ∏ÆÊàëÂõûÁ≠îÂºÄÂ§¥ÁöÑÈóÆÈ¢ò‚Äù ‰ºöÂèëÈÄÅ‰∏Ä‰ªΩÁªô ChatGPT ÁÑ∂ÂêéÂ∞èÁà±ÂêåÂ≠¶Áî® tts ÂõûÁ≠î

## ÊÄªÁªì

- ÂÆåÊàêÈÇ£‰∏ÄÂàªÁ°ÆÂÆûÊå∫ÂºÄÂøÉÔºå‰ΩÜËøáÁ®ã‰∏≠ÂèëÁé∞‰∫ÜÂá†‰∏™Â•ΩÁé©ÁöÑ[ÂçöÂÆ¢](http://javabin.cn/archives/)ÔºåÊÉäËÆ∂‰∫ÜÂÅö revChatGPT ÁöÑÂ≠¶ÁîüÁúüÁâõÈÄºÔºåÂ≠¶‰ºö‰∫ÜÁÑäÊé•ÔºåÂºÄÂßãÂèëÁé∞Á°¨‰ª∂‰πüÊå∫ÊúâÊÑèÊÄùÁöÑÔºå‰∏çÊñ≠ÊäòËÖæÁöÑËøáÁ®ãÊ≤Æ‰∏ßÊúâ‰∏Ä‰∫õÔºå‰ΩÜÊõ¥Â§öÁöÑÊòØÂ≠¶‰π†Êñ∞‰∏úË•øÂ∏¶Êù•ÁöÑÂÖ¥Â•ãÊÑü„ÄÇ
- ÊãÜÊú∫ÂèëÁé∞ÔºåÂ∞èÁà±ÂêåÂ≠¶ÂÜÖÈÉ®ÂÅöÂ∑•Á°ÆÂÆû‰∏çÈîô
- ÊäòËÖæËøáÁ®ã‰∏≠ÁöÑÊÑüÂèóÔºåÂ∞ÜÊù•ËÇØÂÆöÊúâ‰∏ÄÂ§©Ëøô‰∫õÊô∫ËÉΩÈü≥ÁÆ±ÂéÇÂïÜ‰πü‰ºöËÆ≠ÁªÉÂ§ßÊ®°ÂûãÔºåÂ∞ÜÂΩªÂ∫ïÊîπÂèòÊô∫ËÉΩÂÆ∂Â±ÖÔºå‰ªø‰ΩõÁúãÂà∞‰∫ÜÊú™Êù•

## ÂΩ©Ëõã

![image](https://user-images.githubusercontent.com/15976103/219273665-f8c252aa-0b05-4f18-9028-8cada453aea5.png)



---

Áé∞Âú®‰∏çÁî®ÊäìÂåÖ‰∫ÜÔºå‰øÆÊîπ‰∫ÜÊñáÁ´†

---

ÂØπÔºåÊñ∞ÁöÑÁâàÊú¨Ëøô‰∏™ÊöÇÊó∂‰∏çË°å

---

@wsjq5477 ÂèØË°åÔºå‰ΩÜÊòØ‰∏çË¶Å mute-xiaomi

---

‰ºöÈ¢ëÁπÅËØ∑Ê±Ç api, ÂÆπÊòìË¢´ ban Ë¶ÅÊòØ‰∏ÄÁõ¥Ë∑ë

---

> @yihong0618 ËØ∑ÈóÆ‰∏ãÊîæÂ∞èÁå™‰Ω©Â•áÊòØ‰ªÄ‰πàÊµÅÁ®ãüòä

Â∞èÁà±ÂêåÂ≠¶ÔºåÂ∏ÆÊàëÊí≠ÊîæÂ∞èÁå™‰Ω©Â•á



---

ÊòØÁöÑ„ÄÇ

---

ÊòØ

---

echo Êúâ‰∫∫ÂÅöÂá∫Êù•‰∫Ü

---

@deadjoker ‰∏çÈúÄË¶Å„ÄÇ

---

ÂèØ‰ª•ÂêåÁéØÂ¢ÉÈÉ®ÁΩ≤Â§ö‰∏™Âêß

---

ÊúâÊõ¥Â§öÁöÑÊä•Èîô‰ø°ÊÅØ‰πàÔºü@Enchner @liuwx2010 

---

Ê∑ªÂä† arg --verbose

---

> --mute_xiaoai Ëøô‰∏™ÂèÇÊï∞‰∏çËÉΩ‰ΩøÁî®Ôºå‰∏ÄÁî®Â∞±Êä•Èîô MinaServiceÈáå‰∏çÂ≠òÂú®xxxÊñπÊ≥ï ‰æãÂ¶Ç‰∏çÂ≠òÂú® player_get_status ‰∏çÂ≠òÂú®player_pause ÊàëÂéªÊü•‰∫ÜÊ∫êÁ†ÅÁöÑÁ°ÆÊ≤°Êúâ
> 
> Ëøô‰∏™È°πÁõÆÊòØ‰∏çÊòØÊúâÁÇπbug

1. pip uninstall miservice
2. pip install -U miservice_fork
3. ‰ª•Âêé bug Âª∫ËÆÆÂú®ËØ•È°πÁõÆÁöÑ issue ‰∏ãÁïôË®ÄÔºåÈÇ£Ê†∑Â§ßÂÆ∂ÈÉΩËÉΩÁúãÂà∞Ôºå‰Ω†Êêú‰∏ãËøô‰∏™ÔºåÈáåÈù¢‰πüÊúâ‰∫∫ÊèêËøá

---

> ÊàëÈÅáÂà∞‰∫ÜÈóÆÈ¢òÔºå ‰ΩÜÊòØÂ∞ùËØï‰∏ãÊù•Êó†Ê≥ïËß£ÂÜ≥ python3 ÁöÑÁéØÂ¢É „ÄÇ Âú®MiService È°πÁõÆ‰∏≠ËøêË°åÂ¶Ç‰∏ãÂëΩ‰ª§ ./micli.py list ÊàñËÄÖ python3 ./micli.py list ÊàñËÄÖ python3 micli.py list„ÄÇ ÁªôÂá∫Â¶Ç‰∏ãÁöÑÊä•Èîô„ÄÇ `xception on login 2330087479: Cannot connect to host sts.api.io.mi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')] Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection transport, protocol = await self._create_connection_transport( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport await waiter File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete raise handshake_exc File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake self._sslobj.do_handshake() File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake self._sslobj.do_handshake() ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/Users/pdx/wk/AI/Â∞èÁà±AI/MiService/miservice/miaccount.py", line 74, in login serviceToken = await self._securityTokenService( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/pdx/wk/AI/Â∞èÁà±AI/MiService/miservice/miaccount.py", line 114, in _securityTokenService async with self.session.get( File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in **aenter** self._resp = await self._coro ^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request conn = await self._connector.connect( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect proto = await self._create_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection raise last_exc File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection transp, proto = await self._wrap_create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection raise ClientConnectorCertificateError(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host sts.api.io.mi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')] Error https://api.io.mi.com/app/home/device_list: Login failed` Ê±ÇËß£

ssl ÈóÆÈ¢ò
1. Â∞ùËØï‰∏çÁî® vpn
2. Â∞ùËØïÊç¢‰∏™ÁΩëÁªúÔºåÊØîÂ¶ÇÊâãÊú∫ÁÉ≠ÁÇπ